-- MySQL Script generated by MySQL Workbench
-- Mon Mar 25 23:15:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema progWeb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `progWeb` ;

-- -----------------------------------------------------
-- Schema progWeb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `progWeb` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `progWeb` ;

-- -----------------------------------------------------
-- Table `progWeb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progWeb`.`User` ;

CREATE TABLE IF NOT EXISTS `progWeb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nameUser` VARCHAR(45) NOT NULL,
  `passwordUser` VARCHAR(256) NOT NULL,
  `emailUser` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `nameUser_UNIQUE` (`nameUser` ASC) ,
  UNIQUE INDEX `emailUser_UNIQUE` (`emailUser` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progWeb`.`Profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progWeb`.`Profile` ;

CREATE TABLE IF NOT EXISTS `progWeb`.`Profile` (
  `idProfile` INT NOT NULL AUTO_INCREMENT,
  `nameProfile` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfile`),
  UNIQUE INDEX `nameProfile_UNIQUE` (`nameProfile` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progWeb`.`User_has_Profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progWeb`.`User_has_Profile` ;

CREATE TABLE IF NOT EXISTS `progWeb`.`User_has_Profile` (
  `User_idUser` INT NOT NULL,
  `Profile_idProfile` INT NOT NULL,
  `idUser_has_Profile` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idUser_has_Profile`),
  CONSTRAINT `fk_User_has_Profile_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `progWeb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Profile_Profile1`
    FOREIGN KEY (`Profile_idProfile`)
    REFERENCES `progWeb`.`Profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progWeb`.`Module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progWeb`.`Module` ;

CREATE TABLE IF NOT EXISTS `progWeb`.`Module` (
  `idModule` INT NOT NULL AUTO_INCREMENT,
  `nameModule` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModule`),
  UNIQUE INDEX `nameModule_UNIQUE` (`nameModule` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progWeb`.`Module_has_Profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `progWeb`.`Module_has_Profile` ;

CREATE TABLE IF NOT EXISTS `progWeb`.`Module_has_Profile` (
  `Module_idModule` INT NOT NULL,
  `Profile_idProfile` INT NOT NULL,
  `canCreate` TINYINT NOT NULL,
  `canRead` TINYINT NOT NULL,
  `canUpdate` TINYINT NOT NULL,
  `canDelete` TINYINT NOT NULL,
  `idModule_has_Profile` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idModule_has_Profile`),
  CONSTRAINT `fk_Module_has_Profile_Module1`
    FOREIGN KEY (`Module_idModule`)
    REFERENCES `progWeb`.`Module` (`idModule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Module_has_Profile_Profile1`
    FOREIGN KEY (`Profile_idProfile`)
    REFERENCES `progWeb`.`Profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
